-- delete created tables

DROP TABLE Staff CASCADE CONSTRAINTS;
DROP TABLE StaffWorkInfo CASCADE CONSTRAINTS;
DROP TABLE Course CASCADE CONSTRAINTS;
DROP TABLE Department CASCADE CONSTRAINTS;
DROP TABLE Module CASCADE CONSTRAINTS;
DROP TABLE Student CASCADE CONSTRAINTS;
DROP TABLE NextKin CASCADE CONSTRAINTS;
DROP TABLE Performance CASCADE CONSTRAINTS;
DROP TABLE Teaching CASCADE CONSTRAINTS;